version: "3.8"

services:
  enabler:
    image: node:20
    volumes:
      - ./enabler:/home/node/app
    restart: always
    working_dir: /home/node/app
    depends_on:
      - processor
    command:  /bin/sh -c 'npm install && npm run dev -- --host 0.0.0.0 --port 3000'
    env_file:
      - ./enabler/.env
    environment:
      - VITE_PROCESSOR_URL=http://localhost:8080
    ports:
      - 3000:3000
  processor:
    image: node:20
    volumes:
      - ./processor:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./processor/.env
    command: /bin/sh -c 'npm install && npm run watch'
    ports:
      - 8080:8080
  session-finisher:
    image: node:20
    volumes:
      - ./session-finisher:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./session-finisher/.env
    command: /bin/sh -c 'npm install && npm run watch'
    ports:
      - 8090:8090
