version: "3.8"

services:
  checkout-page:
    image: node:20
    volumes:
      - ./enabler:/home/node/app
    restart: always
    working_dir: /home/node/app
    depends_on:
      - processor
    command:  /bin/sh -c 'npm install && npm run dev -- --host 0.0.0.0 --port 3000'
    env_file:
      - ./enabler/.env
    environment:
      - VITE_PROCESSOR_URL=http://localhost:8080
      - VITE_ENABLER_URL=http://localhost:8888/connector-enabler.es.js
    ports:
      - 3000:3000
  enabler:
    image: node:20
    volumes:
      - ./enabler:/home/node/app
    restart: always
    working_dir: /home/node/app
    depends_on:
      - processor
    command:  /bin/sh -c 'npm install && npm run build && npm run start'
    env_file:
      - ./enabler/.env
    environment:
      - VITE_PROCESSOR_URL=http://localhost:8080
    ports:
      - 8888:8080
  processor:
    image: node:20
    volumes:
      - ./processor:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./processor/.env
    command: /bin/sh -c 'npm install && npm run watch'
    ports:
      - 8080:8080
  event-handler:
    image: node:20
    volumes:
      - ./event-handler:/home/node/app
    working_dir: /home/node/app
    env_file:
      - ./event-handler/.env
    command: /bin/sh -c 'npm install && npm run build && npm run start'
    ports:
      - 80:8080
