name: CI

on: [push]

jobs:
  build-enabler:
    name: Build the application for enabler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: enabler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install modules
        run: npm ci

      - name: Perform lint check
        run: npm run check

      - name: Execute build
        run: npm run build

      - name: Execute test case
        run: npm run test

  build-processor:
    name: Build the application for processor
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: processor
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install modules
        run: npm ci

      - name: Perform lint check
        run: npm run lint

      - name: Execute build
        run: npm run build

      - name: Execute test case
        run: npm run test

  build-event-handler:
    name: Build the application for event handler
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: event-handler
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: "20.x"

      - name: Install modules
        run: npm ci

      - name: Perform lint check
        run: npm run lint

      - name: Execute build
        run: npm run build

      - name: Execute test case
        run: npm run test
